# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Lead"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  color:
  height:
  Inner:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  color: 
  height: 
  Inner: 

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
