# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

_editables:
  text:
    italic: true
  block:
    format: p h3
    undo: true
    redo: true
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    image_size_attributes: true
    snippet: true

_snippets:
  alert:
    template: hugo_paired_shortcode_named_args
    inline: true
    definitions:
      shortcode_name: alert
      content_key: inner_text
      named_args:
        - source_key: color
          editor_key: color
          default: danger
          optional: true
          remove_empty: true
          type: string
          allowed_values: &css_colors
            - primary
            - primary-light
            - secondary
            - success
            - info
            - warning
            - danger
            - white
            - light
            - dark
            - blue
            - orange
            - gray-100
            - gray-200
            - gray-300
            - gray-400
            - gray-500
            - gray-600
            - gray-700
            - gray-800
            - gray-900
            - black
        - source_key: title
          editor_key: title
          optional: true
          remove_empty: true
          type: string
    preview:
      text: 'Alert'
      subtext:
        - key: inner_text
        - No text defined
      icon: warning
    _inputs:
      color:
        type: select
        options:
          values: *css_colors

  imgproc:
    template: hugo_paired_shortcode_positional_args
    inline: false
    definitions:
      shortcode_name: imgproc
      content_key: inner_text
      positional_args:
        - editor_key: name
          type: string
        - editor_key: imgProcessing
          type: string
          allowed_values: &imgProcessing
            - Fit
            - Fill
            - Resize
        - editor_key: dimensions
          type: string
    preview:
      text: 'imgproc'
      subtext:
        - key: inner_text
        - No text defined
      icon: image
    _inputs:
      imgProcessing:
        type: select
        options:
          values: *imgProcessing

  pageinfo:
    template: hugo_paired_markdown_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: pageinfo
      content_key: inner_text
      named_args:
        - source_key: color
          editor_key: color
          default: primary
          optional: true
          remove_empty: true
          type: string
          allowed_values: &css_colors
            - primary
            - primary-light
            - secondary
            - success
            - info
            - warning
            - danger
            - white
            - light
            - dark
            - blue
            - orange
            - gray-100
            - gray-200
            - gray-300
            - gray-400
            - gray-500
            - gray-600
            - gray-700
            - gray-800
            - gray-900
            - black
    preview:
      text: 'Page info'
      subtext:
        - key: inner_text
        - No text defined
      icon: info
    _inputs:
      color:
        type: select
        options:
          values: *css_colors
  
  card:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: card
      content_key: inner_text
      named_args:
        - source_key: header
          editor_key: header
          optional: true
          remove_empty: true
          type: string
        - source_key: title
          editor_key: title
          optional: true
          remove_empty: true
          type: string
        - source_key: subtitle
          editor_key: subtitle
          optional: true
          remove_empty: true
          type: string
        - source_key: footer
          editor_key: footer
          optional: true
          remove_empty: true
          type: string
    preview:
      text: 'Card'
      subtext:
        - key: title
        - No text defined
      icon: page

  cardpane:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: cardpane
      content_key: card
    preview:
      text: 'cardpane'
      subtext:
        - A wrapper used to display multiple cards
      icon: dashboard
    _inputs:
      card:
        type: markdown
        options:
          snippet: true
 

  card-code:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: card-code
      content_key: inner_text
      named_args:
        - source_key: header
          editor_key: header
          optional: true
          remove_empty: true
          type: string
        - source_key: lang
          editor_key: lang
          optional: true
          remove_empty: true
          type: string
    preview:
      text: 'card-code'
      subtext:
        - A card used for displaying code
      icon: tab

  tab:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: tab
      content_key: inner_text
      named_args:
        - source_key: header
          editor_key: header
          optional: true
          remove_empty: true
          type: string
        - source_key: disabled
          editor_key: disabled
          optional: true
          remove_empty: true
          type: boolean
    preview:
      text: 'tab'
      subtext:
        - key: header
        - No text defined
      icon: tab

  tabpane:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: tabpane
      content_key: tab
      named_args:
        - source_key: header
          editor_key: header
          optional: true
          remove_empty: true
          type: string
        - source_key: lang
          editor_key: lang
          optional: true
          remove_empty: true
          type: string
    preview:
      text: 'tabpane'
      subtext:
        - A pane used for displaying tabs
      icon: dashboard
    _inputs:
      tab:
        type: markdown
        options:
          snippet: true

  iframe:
    template: hugo_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: iframe
      named_args:
        - source_key: src
          editor_key: src
          optional: false
          type: string
        - source_key: width
          editor_key: width
          optional: true
          remove_empty: true
          type: string
        - source_key: tryautoheight
          editor_key: tryautoheight
          optional: true
          remove_empty: true
          type: boolean
        - source_key: style
          editor_key: style
          optional: true
          remove_empty: true
          type: string
        - source_key: sandbox
          editor_key: sandbox
          optional: true
          remove_empty: true
          type: boolean 
        - source_key: name
          editor_key: name
          optional: true
          remove_empty: true
          type: string 
        - source_key: id
          editor_key: id
          optional: true
          remove_empty: true
          type: string 
        - source_key: sub
          editor_key: sub
          optional: true
          remove_empty: true
          type: string 
    preview:
      text: 'iframe'
      subtext:
        - Embed a webpage on your site
      icon: dashboard

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    output: true
    filter: strict
    parse_branch_index: true
    path: content/en
    icon: home
    _enabled_editors:
      - visual
      - content
  blog:
    path: content/en/blog
    output: true
    icon: auto_stories
    _enabled_editors:
      - content
      - visual
  about:
    path: content/en/about
    output: true
    icon: psychology
    _enabled_editors:
      - visual
      - content
  community:
    path: content/en/community
    output: true
    icon: groups
    _enabled_editors:
      - content
      - visual
  docs:
    path: content/en/docs
    output: true
    icon: description
    _enabled_editors:
      - content
      - visual

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source:
  archetypes: archetypes
  assets: assets
  content: content/en
  pages: content/en
  publish: public
  config:

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
