# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    output: true
    filter: strict
    parse_branch_index: true
    path: content/en
    icon: auto_stories
  blog:
    path: content/en/blog
    output: true
    icon: library_books
  about:
    path: content/en/about
    output: true
    icon: psychology
  community:
    path: content/en/community
    output: true
    icon: groups
    _enabled_editors:
      - visual
  docs:
    path: content/en/docs
    output: true
    icon: description

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source:
  archetypes: archetypes
  assets: assets
  content: content/en
  pages: content/en
  publish: public
  config:

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
