# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

_editables: &md_editables
  text:
    italic: true
  block:
    format: p h3
    undo: true
    redo: true
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    image_size_attributes: true
    snippet: true

_snippets:
  alert:
    template: hugo_paired_shortcode_named_args
    inline: true
    definitions:
      shortcode_name: alert
      content_key: message
      named_args:
        - source_key: color
          editor_key: color
          default: danger
          optional: true
          remove_empty: true
          type: string
          allowed_values: &css_colors
            - primary
            - primary-light
            - secondary
            - success
            - info
            - warning
            - danger
            - white
            - light
            - dark
            - blue
            - orange
            - gray-100
            - gray-200
            - gray-300
            - gray-400
            - gray-500
            - gray-600
            - gray-700
            - gray-800
            - gray-900
            - black
        - source_key: title
          editor_key: title
          optional: true
          remove_empty: true
          type: string
    preview:
      text: 
        - key: title
        - An alert
      subtext:
        - key: message
        - No text defined
      icon: warning
      gallery:
        - key: message
        - text: An alert
      view: gallery
    picker_preview:
      text: Alert
      subtext: An alert with color options
      icon: warning
      gallery: 
        image: /preview-images/alert.png
        text: An alert with color options
    _inputs:
      color:
        type: select
        options:
          values: *css_colors
      message:
        label: Alert Message
        comment: The content of your alert message.
        type: text
      title:
        label: Alert Title
        comment: The title of your alert message.
        type: text

  pageinfo:
    template: hugo_paired_markdown_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: pageinfo
      content_key: message
      named_args:
        - source_key: color
          editor_key: color
          default: primary
          optional: true
          remove_empty: true
          type: string
          allowed_values: &css_colors
            - primary
            - primary-light
            - secondary
            - success
            - info
            - warning
            - danger
            - white
            - light
            - dark
            - blue
            - orange
            - gray-100
            - gray-200
            - gray-300
            - gray-400
            - gray-500
            - gray-600
            - gray-700
            - gray-800
            - gray-900
            - black
    preview:
      text:
        - key: message
        - Page Info
      subtext:
        - key: color
        - No color defined
      icon: info
      gallery: 
        image: /preview-images/pageinfo.png
        text: A banner to display page info.
      view: gallery
    picker_preview:
      text: Page Info
      subtext: A banner to display page info.
      icon: info
      gallery: 
        image: /preview-images/pageinfo.png
        text: A banner to display page info.
    _inputs:
      color:
        type: select
        options:
          values: *css_colors
      message:
        label: Message
        comment: The message to display.
        type: text
  
  card:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: card
      content_key: message
      named_args:
        - editor_key: header
          optional: true
          remove_empty: true
        - source_key: title
          editor_key: title
          optional: true
          remove_empty: true
          type: string
        - source_key: subtitle
          editor_key: subtitle
          optional: true
          remove_empty: true
          type: string
        - source_key: footer
          editor_key: footer
          optional: true
          remove_empty: true
          type: string
    preview:
      text:
        - key: title
        - Card
      subtext:
        - key: subtitle
        - key: message
        - No text defined
      icon: tab
      gallery: 
        image: /preview-images/card.png
        text: A basic card
      view: gallery
    picker_preview:
      text: Card
      subtext: A basic card
      icon: tab
      gallery: 
        image: /preview-images/card.png
        text: A basic card
    _inputs:
      message:
        label: Card Content
        comment: The content of the card.
        type: markdown
        options:
            blockquote: true
            bold: true
            format: p h1 h2 h3 h4 h5 h6 pre address div
            italic: true
            strike: true
            subscript: true
            superscript: true
            underline: true
            link: true
            bulletedlist: true
            indent: true
            numberedlist: true
            outdent: true
            code: true
            embed: true
            horizontalrule: true
            image: true
            table: true
            undo: true
            redo: true
            removeformat: true
            copyformatting: true
            left: align-left
            center: align-center
            right: align-right
            justify: align-justify
            image_size_attributes: true
            snippet: true
      header:
        label: Header
        comment: The card header.
        type: text
      title:
        label: Title
        comment: The card title.
        type: text
      subtitle:
        label: Subtitle
        comment: The card subtitle.
        type: text
      footer:
        label: Footer
        comment: The card footer.
        type: text

  cardpane:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: cardpane
      content_key: card
    preview:
      text: Card Pane
      subtext:
        - A wrapper used to display multiple cards
      icon: dashboard
      gallery: 
        image: /preview-images/cardpane.png
        text: A wrapper for cards to be displayed next to each other
      view: gallery
    picker_preview:
      text: Card Pane
      subtext: A wrapper for cards to be displayed next to each other
      icon: dashboard
      gallery: 
        image: /preview-images/cardpane.png
        text: A wrapper for cards to be displayed next to each other
    _inputs:
      card:
        label: Cards
        comment: Add individual cards to occupy this card pane
        type: markdown
        options:
          snippet: true
    
  tab:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: tab
      content_key: content
      named_args:
        - source_key: header
          editor_key: header
          optional: true
          remove_empty: true
          type: string
        - source_key: lang
          editor_key: lang
          optional: true
          remove_empty: true
          type: string
        - source_key: disabled
          editor_key: disabled
          optional: true
          remove_empty: true
          type: boolean
    preview:
      text: 
        - key: header
        - No header defined
      subtext:
        - key: content
        - No content defined
      icon: tab
      gallery: 
        image: /preview-images/tabpane.png
        text: A tab to be used inside a tabpane wrapper
      view: gallery
    picker_preview:
      text: Tab
      subtext: A tab to be used inside a tabpane wrapper
      icon: tab
      gallery: 
        image: /preview-images/tabpane.png
        text: A tab to be used inside a tabpane wrapper
    _inputs:
      content:
        label: Tab Content
        comment: The content of the tab
        type: markdown
        options:
          blockquote: true
          bold: true
          format: p h1 h2 h3 h4 h5 h6 pre address div
          italic: true
          strike: true
          subscript: true
          superscript: true
          underline: true
          link: true
          bulletedlist: true
          indent: true
          numberedlist: true
          outdent: true
          code: true
          embed: true
          horizontalrule: true
          image: true
          table: true
          undo: true
          redo: true
          removeformat: true
          copyformatting: true
          left: align-left
          center: align-center
          right: align-right
          justify: align-justify
          image_size_attributes: true
      header:
        label: Tab Header
        comment: The header for this individual tab
        type: text
      lang:
        label: Language
        comment: The language to be used for syntax highlighting in this tab. This field can be left blank if 'Header Specifies Language' is true in Tab Pane.
        type: text
      disabled:
        label: Disabled
        comment: Disable this tab to make it unclickable
        type: checkbox
        
  tabpane:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: tabpane
      content_key: tab
      named_args:
        - source_key: text
          editor_key: text
          optional: false
          remove_empty: false
          type: boolean
        - source_key: right
          editor_key: right
          optional: true
          remove_empty: true
          type: boolean
          default: true
        - source_key: langEqualsHeader
          editor_key: langEqualsHeader
          optional: true
          remove_empty: true
          type: boolean
          default: false
        - source_key: persistLang
          editor_key: persistLang
          optional: true
          remove_empty: true
          type: boolean
    preview:
      text: Tab Pane
      subtext: Wraps a group of tabs
      icon: dashboard
      gallery:
        image: /preview-images/tabpane.png
        text: A set of tabs
      view: gallery
    picker_preview:
      text: Tab Pane
      subtext: A set of tabs
      icon: dashboard
      gallery: 
        image: /preview-images/tabpane.png
        text: A set of tabs
    _inputs:
      tab:
        label: Tabs
        comment: Add tabs to the tabpane.
        type: markdown
        options:
          snippet: true
      text:
        label: Text
        comment: If the contents of your tabs should be rendered as plain text rather than code.
        type: checkbox
      right:
        label: Right Align
        comment: Align the tabs to the right of the tabpane
        type: checkbox
      langEqualsHeader:
        label: Header Specifies Language
        comment: If the header of each tab is the programming language to be used for syntax highlighting in the tab contents. Language can also be specified inside each tab independently to tab header.
        type: checkbox
      persistLang:
        label: Persist Language
        comment: By default, the language of the selected tab is stored and preserved between different browser sessions. If the content length within your tabs differs greatly, this may lead to unwanted scrolling when switching between tabs. To disable this unwanted behaviour, check False.
        type: checkbox

  iframe:
    template: hugo_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: iframe
      named_args:
        - source_key: src
          editor_key: src
          optional: false
          type: string
        - source_key: width
          editor_key: width
          optional: true
          remove_empty: true
          type: string
          default: 80%
        - source_key: tryautoheight
          editor_key: tryautoheight
          optional: true
          type: boolean
          default: false
        - source_key: style
          editor_key: style
          optional: true
          remove_empty: true
          type: string
          default: min-height:98vh; border:none;
        - source_key: sandbox
          editor_key: sandbox
          optional: true
          remove_empty: true
          type: boolean 
          default: false
        - source_key: name
          editor_key: name
          optional: true
          remove_empty: true
          type: string 
        - source_key: id
          editor_key: id
          optional: true
          remove_empty: true
          type: string 
        - source_key: sub
          editor_key: sub
          optional: true
          remove_empty: true
          type: string
          default: "Your browser cannot display embedded frames. You can access the embedded page via the following link:"
    preview:
      text: iframe
      subtext:
        - Embed a webpage on the page
      icon: dashboard
      gallery: 
        image: /preview-images/iframe.png
        text: Embed a site on the page
      view: gallery
    picker_preview:
      text: iframe
      subtext: Embed a site on the page
      icon: dashboard
      gallery: 
        image: /preview-images/iframe.png
        text: Embed a site on the page
    _inputs:
      src:
        label: Source
        comment: The URL of the site to be used in the iframe.
        type: url
      width:
        label: Width
        comment: The width of the iframe on the page. Accepts any CSS value.
        type: text
      tryautoheight:
        label: Auto Height
        comment: If true the shortcode tries to calculate the needed height for the embedded content using JavaScript. Only possible if the embedded content is on the same domain.
        type: switch
      style:
        label: Style
        comment: CSS styles for the iframe. min-height:98vh; is a backup if Auto Height doesn’t work. border:none; removes the border from the iframe.
        type: textarea
      sandbox:
        label: Sandbox
        comment: Switch the sandbox completely on
        type: checkbox
      name:
        label: Name
        comment: Specify the name of the iframe.
        type: text
      id:
        label: ID
        comment: Set the ID of the iframe.
        type: text
      sub:
        label: Sub
        comment: The text displayed (in addition to the embedded URL) if the user’s browser can’t display embedded frames.
        type: textarea

  swaggerui:
    template: hugo_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: swaggerui
      named_args:
        - source_key: src
          editor_key: src
          optional: false
          type: string
    preview:
      text: Swagger UI
      subtext:
        - Placed inside a page with the `swagger` layout, this will render Swagger UI using any OpenAPI YAML or JSON file as source.
      icon: description
      gallery: 
        image: /preview-images/swaggerui.png
        text: Placed inside a page with the `swagger` layout, this will render Swagger UI using any OpenAPI YAML or JSON file as source.
      view: gallery
    picker_preview:
      text: Swagger UI
      subtext: Placed inside a page with the `swagger` layout, this will render Swagger UI using any OpenAPI YAML or JSON file as source.
      icon: description
      gallery: 
        image: /preview-images/swaggerui.png
        text: Placed inside a page with the `swagger` layout, this will render Swagger UI using any OpenAPI YAML or JSON file as source.
    _inputs:
      src:
        label: Source
        comment: The OpenAPI YAML or JSON file used as the source file.
        type: file  

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    output: true
    path: content/en
    icon: home
    _enabled_editors:
      - visual
      - content
    text_key: 
    description: Collection of pages.
    schemas:
      default:
        path: schemas/main.md
        create:
          path: '{title|slugify}/_index.md'
        _inputs:
          type: select
          options:
            values:
              - page
              - docs
              - blog
      bookshop_main:
        path: schemas/bookshop_main.md
        create:
          path: '{title|slugify}/_index.md'
  blog:
    path: content/en/blog
    output: true
    icon: auto_stories
    schemas:
      default:
        path: schemas/blog/post.md
        name: New Blog Post
      post_list:
        path: schemas/blog/post_list.md
        name: Post Index Page
        create:
          path: '[relative_base_path]/{title|slugify}/_index.md'
    _enabled_editors:
      - content
      - visual
  about:
    path: content/en/about
    output: true
    icon: psychology
    _enabled_editors:
      - visual
      - content
  community:
    path: content/en/community
    output: true
    icon: groups
    _enabled_editors:
      - content
      - visual
  docs:
    path: content/en/docs
    output: true
    icon: description
    schemas:
      default:
        name: Docs Page
        path: schemas/docs/default.md
      index:
        name: Docs Section
        path: schemas/docs/default.md
        create:
          path: '[relative_base_path]/{title|slugify}/_index.md'
    _enabled_editors:
      - content
      - visual

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static
  source:
  archetypes: archetypes
  assets: assets
  content: content/en
  pages: content/en
  publish: public
  config:

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC

_inputs:
  weight:
    label: Weight
    comment: Sets the weight of the menu item. The higher the weight, the further down the menu item is.
    type: number
