contentDir: content/en

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
enableGitInfo: true

taxonomies:
  tag: tags
  category: categories
  
params:
  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
    
permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
  
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
  
services:
  googleAnalytics:
    id: UA-00000000-0
    
languages:
  en:
    title: Goldydocs
    description: A Docsy example site
    languageName: English
    weight: 1
  'no':
    title: Goldydocs
    description: Docsy er operativsystem for skyen
    languageName: Norsk
    contentDir: content/no
    time_format_default: 02.01.2006
    time_format_blog: 02.01.2006
  fa:
    title: اسناد گلدی
    description: یک نمونه برای پوسته داکسی
    languageName: فارسی
    contentDir: content/fa
    time_format_default: 2006.01.02
    time_format_blog: 2006.01.02
    
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
    
outputs:
  section:
    - HTML
    - print
    - RSS
    
module:
  replacements: components.local -> ../component-library
  hugoVersion:
    extended: true
    min: 0.75.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
    - path: components.local
    - path: github.com/cloudcannon/bookshop/hugo/v3
