# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Section"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    text: Inner text
    col_id: light
    # Height can be one of: auto, min, med, max, full.
    height:
    type: section
    Inner: This is the section shortcode block

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
