# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Cover"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: A title
  subtitle: A subtitle
  text: Inner text
  col_id: warning
  background_image: /featured-background.jpg
  # anchors are for .Fit hugo image method which currently don't work
  image_anchor: 
  logo_image: http://placekitten.com/70/70
  logo_anchor:
  # Height can be one of: auto, min, med, max, full.
  height: med
  byline: A byline

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
