# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Feature"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: A title
  text: Some text
  url: https://github.com/gohugoio/hugo
  url_text: Link text

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: A title
  text: Some text
  url: https://github.com/gohugoio/hugo
  url_text: Link text
  
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
