# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Community_links"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text:
    right:
      right_heading: Develop and Contribute
      right_sub_heading: "If you want to get more involved by contributing to Goldydocs, join us here:"
      right_ending: You can find out how to contribute to Goldydocs in our 
      right_ending_link: /docs/contribution-guidelines/
      right_ending_link_text: Contribution Guidelines 
    left:
      left_heading: Learn and Connect
      left_sub_heading: "Using or want to use Goldydocs? Find out more here:"
      left_ending:
      left_ending_link:
      left_ending_link_text:
  links:
    user:
      - name: User mailing list
        url: 'https://example.org/mail'
        icon: fa fa-envelope
        desc: Discussion and help from your fellow users
      - name: Twitter
        url: 'https://example.org/twitter'
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
      - name: Stack Overflow
        url: 'https://example.org/stack'
        icon: fab fa-stack-overflow
        desc: Practical questions and curated answers
    developer:
      - name: GitHub
        url: 'https://github.com/google/docsy'
        icon: fab fa-github
        desc: Development takes place here!
      - name: Slack
        url: 'https://example.org/slack'
        icon: fab fa-slack
        desc: Chat with other project developers
      - name: Developer mailing list
        url: 'https://example.org/mail'
        icon: fa fa-envelope
        desc: Discuss development issues around the project


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text:
    right:
      right_heading: Develop and Contribute
      right_sub_heading: "If you want to get more involved by contributing to Goldydocs, join us here:"
      right_ending: You can find out how to contribute to Goldydocs in our 
      right_ending_link: /docs/contribution-guidelines/
      right_ending_link_text: Contribution Guidelines 
    left:
      left_heading: Learn and Connect
      left_sub_heading: "Using or want to use Goldydocs? Find out more here:"
      left_ending: ""
      left_ending_link: ""
      left_ending_link_text: ""
  links:
    user:
      - name: User mailing list
        url: 'https://example.org/mail'
        icon: fa fa-envelope
        desc: Discussion and help from your fellow users
      - name: Twitter
        url: 'https://example.org/twitter'
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
      - name: Stack Overflow
        url: 'https://example.org/stack'
        icon: fab fa-stack-overflow
        desc: Practical questions and curated answers
    developer:
      - name: GitHub
        url: 'https://github.com/google/docsy'
        icon: fab fa-github
        desc: Development takes place here!
      - name: Slack
        url: 'https://example.org/slack'
        icon: fab fa-slack
        desc: Chat with other project developers
      - name: Developer mailing list
        url: 'https://example.org/mail'
        icon: fa fa-envelope
        desc: Discuss development issues around the project

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
