# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Link_down"
  description: An arrow linking to an id/
  icon: arrow
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  id:
  color: 
  
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  id:
  color:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
